#import "./common.gql"

subscription OnProjectCreated {
  projectCreated {
      ...ProjectInformationWithMembers
  }
}

subscription OnProjectEdited {
  projectEdited {
    ...ProjectInformationWithMembers
  }
}

subscription OnProjectDeleted {
  projectDeleted {
    ...ProjectInformationWithMembers
  }
}
