"""make showcase id unique

Revision ID: 26f36ffab4d9
Revises: 632189d9418c
Create Date: 2020-11-28 15:34:28.886671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26f36ffab4d9'
down_revision = '632189d9418c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'teams', ['showcase_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='unique')
    # ### end Alembic commands ###
