"""fix backpropogate

Revision ID: 632189d9418c
Revises: 7d23fcd11240
Create Date: 2020-11-28 15:26:41.009812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '632189d9418c'
down_revision = '7d23fcd11240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
