fragment MemberInformation on ShowcaseMember {
  username
  account {
    discordId
  }
}

fragment ProjectInformation on ShowcaseProject {
  id
  name
  type
  description
  podChannel: metadataValue(key: "pod.channel")
  podName: metadataValue(key: "pod.name")
  podMessage: metadataValue(key: "pod.message")
}

fragment ProjectInformationWithMembers on ShowcaseProject {
  ...ProjectInformation
  members {
    ...MemberInformation
  }
}
