#import "./index.gql"
subscription OnMemberRemoved {
  memberRemoved {
    ...MemberInformation
    project {
        ...ProjectInformation
    }
  }
}

subscription OnMemberAdded {
  memberAdded {
    ...MemberInformation
      project {
          ...ProjectInformation
      }
  }
}
